version: '3'

services:

  caddy:
    build:
      # need to include files from parent dir (see Dockerfile)
      context: ../
      dockerfile: docker/caddy/Dockerfile
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"

  dannet:
    build:
      # need to include files from parent dir (see Dockerfile)
      context: ../
      dockerfile: docker/dannet/Dockerfile
    restart: unless-stopped
    volumes:
      - ${DANNET_DB}:/etc/dannet/db
      - ${DANNET_BOOTSTRAP}:/etc/dannet/bootstrap
      - ${DANNET_EXPORT}:/etc/dannet/export
    ports:
      - "3456:3456"
